services:
  canis:
    build:
      target: canis
    ports:
      - 127.0.0.1:3003:3000
    environment:
      - MEDIA_PATH=/webm
      - PORT=3000
      - BIND_ADDRESS=0.0.0.0
      - AUTH_COOKIE_NAME=
      - AUTH_COOKIE_VALUE=
    volumes:
      - /video:/webm
